---
# Source: cluster-api-aws/templates/aws-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: cimwgkuk7
  namespace: cimwgkuk7
spec:
  region: ap-northeast-2
  sshKeyName: tks-seoul
  bastion:
    enabled: false
